server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/countries {
    proxy_pass http://geo-service:3001/api/countries;
  }

  location /api/quiz/ {
    proxy_pass http://quiz-service:3002/api/quiz/;
  }

  location /api/auth/ {
    proxy_pass http://auth-service:3003/api/auth/;
  }
}
