apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-service
  namespace: quiz-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-service
  template:
    metadata:
      labels:
        app: geo-service
    spec:
      containers:
        - name: geo-service
          image: geo-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
