apiVersion: v1
kind: Service
metadata:
  name: world-quiz
  namespace: quiz-project
spec:
  selector:
    app: world-quiz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
