stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: node:20-alpine
  script:
    - npm install
    - npm run lint

test:
  stage: test
  image: node:20-alpine
  script:
    - npm install
    - npm run test

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build
